# Generated by Django 4.2.5 on 2023-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=100)),
                ('eduakia', models.CharField(max_length=300)),
                ('noizsSortua', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
