# Generated by Django 4.2.5 on 2023-09-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='eduakia',
            new_name='edukia',
        ),
    ]
