# Generated by Django 4.2.5 on 2023-09-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_eduakia_post_edukia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('jaiotzaData', models.DateField(blank=True)),
                ('gmail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='AutoreDefault', on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
