# Generated by Django 4.2.5 on 2023-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigarrenEskukoDenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prezioa',
            field=models.IntegerField(),
        ),
    ]
