# Generated by Django 4.2.5 on 2023-09-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigarrenEskukoDenda', '0002_alter_post_prezioa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='abizena',
            new_name='izenAbizenak',
        ),
        migrations.RemoveField(
            model_name='author',
            name='izena',
        ),
    ]
