# Generated by Django 4.2.5 on 2023-09-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BigarrenEskukoDenda', '0003_rename_abizena_author_izenabizenak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BigarrenEskukoDenda.author'),
        ),
    ]
